"App_Leave_Application As screen.'tabletAutoLayout_HeaderMainFooter_ver1.0'":
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)
    OnVisible: |-
        =// 获取本月第一天
        Set(firstDayOfMonth, DateValue(Text(Year(Now())) & "-" & Text(Month(Now())) & "-01"));
        // 获取当前记录的编号
        Set(num, CountRows(
        
            Filter(
        
                OA_Purchase_Execution_Process,
                DateValue(Created) >= firstDayOfMonth && DateValue(Created) <= Now()
        
            )
        
        ));
        
         
        
        Set(num, num + 1);
        
         
        
        Set(
        
            
        
                BDRequestNo, "BDBV-" & Text(
        
                    Now(),
        
                    "yyyymmdd"
        
                ) & "-" & num
        
            
        
        );

    ScreenContainer4_16 As groupContainer.verticalAutoLayoutContainer:
        BorderColor: =RGBA(255, 255, 255, 1)
        BorderThickness: =5
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

    help_6 As help:
        CallTeams: |
            =Set(sendMessage,true);
            Patch(teams,Defaults(teams),{Title:"teams",User:CurrenUserEmail,Operation:Text(showEmailhelp)});
        HideContacts: =Set(showhelp,false);Set(showEmailhelp,false);
        IsEmail: =showEmailhelp
        IsShow: =showhelp
        IsShowMessage: =sendMessage
        ShowContacts: =Set(showhelp,true);Set(sendMessage,false);Set(showEmailhelp,false)
        X: =Parent.Width-260
        Y: =Parent.Height-300
        ZIndex: =2

    Lbl_backGroud_1 As label:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        Color: =RGBA(51, 51, 51, 1)
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Fill: =RGBA(230, 230, 230, 0.6)
        FocusedBorderThickness: =4
        Font: =Font.'Segoe UI'
        Height: =Parent.Height
        PaddingRight: =6.76
        PaddingTop: =6.76
        Size: =17.57
        Text: =
        Visible: =ToConfirm
        Width: =Parent.Width
        X: =0.00
        ZIndex: =3

    Image16_2 As image:
        BorderColor: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.None
        BorderThickness: =2
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =500
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverFill: =RGBA(0, 0, 0, 0)
        Image: =subiting
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedFill: =RGBA(0, 0, 0, 0)
        Visible: =ShowWaiting
        Width: =500
        X: =(Parent.Width - Self.Width) / 2
        Y: =(Parent.Height - Self.Height) / 2
        ZIndex: =42

    GroupTrace As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =62

    Group_Confirm_1 As group:
        Height: =5
        Width: =5
        X: =483
        Y: =284
        ZIndex: =67

