"Sub_Leave_Application As screen.'tabletAutoLayout_HeaderMainFooter_ver1.0'":
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)
    OnVisible: |-
        =// 获取本月第一天
        Set(firstDayOfMonth, DateValue(Text(Year(Now())) & "-" & Text(Month(Now())) & "-01"));
        // 获取当前记录的编号
        Set(num, CountRows(
        
            Filter(
        
                OA_Purchase_Execution_Process,
                DateValue(Created) >= firstDayOfMonth && DateValue(Created) <= Now()
        
            )
        
        ));
        
         
        
        Set(num, num + 1);
        
         
        
        Set(
                BDRequestNo, "BDBV-" & Text(
        
                    Now(),
        
                    "yyyymmdd"
        
                ) & "-" & num
        
            
        
        );
        
        If(IsBVAEdit,EditForm(Form1_5),NewForm(Form1_5));

